### ISSUE TITLE
Have a good day~!

### ISSUE THREAD

**Issue by histeria25** [suakii/withyou#5]
이슈는 누구나 생성 가능한가 함 해봤슈~~

**Comment by suakii** [comment]
오호 자신의 이슈를 닫는것도 가능 하군요.^^ 
저도 잘 몰라서 암튼 신가하네요.

**Comment by histeria25** [comment]
닫힌 이슈에도 코멘트가 달리네요. 그럼 오픈과 클로즈의 차인 뭘까요?

버튼이 두개가 있긴 하네요.
Reopen and Comment랑 Comment

닫았다가 다시 열 수도 있어서 그런가보네용
